# Non-technical summary

## Definition
The percentage of people at high risk from climate-related hazards globally is defined as the number of people globally who are both exposed to a set of key climate-related hazards (floods, droughts, cyclones, and heat-waves) and are also highly vulnerable (i.e., have a propensity to be adversely affected or unable to cope with the impacts), as a share of global population. Specifically, people are counted as at high risk from climate-related hazards if they are exposed to at least one hazard and are identified as highly vulnerable on at least one dimension of vulnerability.

This indicator follows the traditional risk framework in which risk is the combination of hazard, exposure, and vulnerability. The hazard is the potential occurrence of an extreme event; exposure is the people affected in the location of the hazard; and vulnerability is the propensity or predisposition of these people to be adversely af-fected.  Here vulnerability is proxied by a set of indicators measuring (1) the physical propensity to experience severe losses (proxied by the lack of mobility and access to basic infrastructure services, such as water and electricity) and (2) the inability to cope with and recover from losses (proxied by low income, not having educa-tion, not having access to financial services and not having access to social protection). Figure 1 summarizes the measure.

The indicator currently considers a subset of climate hazards using historical data, a subset of vulnerability di-mensions, and an aggregation methodology similar to approaches used for multidimensional poverty measures. The methodology will be revised over time as new data are collected and methodologies.

## Development relevance
At any one time some households are experiencing income growth and moving out of poverty, whilst others are experiencing setbacks and falling into poverty (Dang and Dabalen, 2018). Poverty reduction requires a focus on both advancing welfare gains and protecting households from setbacks. Climate-related hazards are one type of setback experienced by households and are increasing in frequency with climate change (Hallegatte et al., 2016). Not only do these extreme weather events increase poverty when they occur, they cast a long shadow on welfare, as they can result in lost assets and investments that limit welfare gains for many years to come. Additionally, highly vulnerable households sometimes engage in costly behavior to avoid or respond to climate-related hazards, such as reduced health or education spending or forced sale of assets, which can af-fect people’s – and especially children’s – prospects for decades.

People with low incomes, with limited access to resources and basic services, and in fragile and conflict-affected contexts are most at risk when facing these extreme weather events.  This indicator tracks those who are at high risk from these extreme weather events, and reducing this global number is important for achieving suc-cessful development and poverty reduction.  This indicator accordingly supports the ongoing work to measure progress on the World Bank’s new vision of “a world free of poverty on a livable planet”. 
