# Limitations

Measuring risk from climate hazards is a complex and data intensive endeavor that requires estimating where climate-related hazards exist, the level of exposure of populations and assets, and the extent that those exposed would be vulnerable or adversely affected. The proposed methodology is a first step, and it will be improved over time along three dimensions:
*	*Coverage*. The first version of the indicator will cover 80 countries, representing 80 percent of the world population, and we will work to expand coverage to new countries over time. 
*	*Lag and updating*. The first version of the indicator will be for 2021, due to lags in some inputs into the indicator. It will be updated annually based on the latest data available, and methodologies to reduce the lag through nowcasting will be explored.
*	*Methodology*. The methodology has limits – the limits are discussed below in details – and will be improved over time, both in terms of scope (adding new relevant factors of vulnerability, for instance) and precision (what are the best metrics for each factor of vulnerability).

A first methodological challenge is that it is challenging to measure the expected economic and welfare costs of events that have not occurred yet. A full assessment requires a full understanding of the costs of each type of event aggregated in a probabilistic framework. The knowledge and data to make a full assessment globally is not available although approaches that consider some of the losses for some hazards are available (as in Hallegatte et al., 2017). This indicator does not attempt to estimate the total impacts (on income, consumption, or welfare), but instead identify populations at high risk, considering the probability of a given set of risks and proxies for high vulnerability. Proxies are characteristics of households that are observed today and are highly correlated with vulnerability or the likelihood of large losses from extreme weather events. Although simpler to calculate and explain than a full risk assessment, this approach is still a complex, data intensive measure. 

At one extreme, everybody is at risk from climate hazards, at least to some extent. The objective of this indicator is therefore to identify the people in the world who are at extremely high risk. The selection of the right thresholds and dimensions of exposure and vulnerability depends on the use of the indicator and the objective of its measure. Some of the limitations of the choices made and the data available to measure this are listed below. While clear choices need to be made in this methodology to produce a global figure for people at high risk from climate-related hazards, the underlying data and methodology supporting this indicator allow for wider analysis that include different vulnerability definitions (e.g., less extreme) and various approaches to measuring exposure (e.g., extreme event definition, return periods).  

1. **Hazard:**
    a. *Focus on severe climate events:* The indicator only reflects people exposed to severe weather events. The thresholds used to estimate these numbers were selected to reflect weather events that cause significant damage, even though low-intensity high-frequency events can still cause substantial impacts on poverty, perhaps cumulatively larger than extreme ones (Hallegatte et al., 2020). The global figure reported for this corporate scorecard indicator does not consider events of all intensities nor all types of events, so it is important to note they do not represent the total number of people whose welfare may be impacted by weather events. The focus is also on climate hazards, not environmental risks per se (for example, air pollution is not included).
    b. *Lack of equivalence across event types:* Given climate events affect different dimensions of wellbeing—loss of life, loss of assets, loss of incomes—it is impossible to select thresholds so that the various events are equally “costly” without making difficult comparisons of loss of life and loss of incomes and income streams across time. While each event is considered severe for each hazard-type considered, there is no attempt to state that they are equally costly.

2. **Exposure:** the focus of the measure is on direct exposure to climate-related events. The indicator focuses on who is in the path of an event, rather than considering who may experience indirect effects such as disruption to markets, price fluctuations, or the consequences of damage to infrastructure. Moreover, the calculation method does not consider the cascading effects that often follow disasters, like propagation of impacts through supply chains, migrations from affected areas, or the outbreak of diseases that can sometimes occur in the aftermath of such events. While this means that this measure is necessarily an underestimate of the people at risk, it nevertheless allows to monitor the people exposed to the direct effect of a climate-related event, which is the driver of and a proxy for indirect impacts (if there is no population directly exposed, then there is no indirect exposure either). 

3. **Vulnerability:** the approach to identifying who is vulnerable gives an equal importance to each dimension (e.g., access to infrastructure and financial inclusion). We acknowledge that different dimensions can be more important, but also that the importance of each dimension is context and hazard specific, and that this complexity cannot be captured with the selected methodology. The remaining limitations on the vulnerability measurement relate to the data availability: 
    a. *Subnational data:* Measures of vulnerability are typically available for subnational administrative regions, which are much larger than the grids for which exposure is known. When overlaying the two, an assumption is made that the exposed and non-exposed in the subnational unit have the same characteristics (i.e., that exposure and vulnerability are not correlated). This assumption is more plausible for smaller and more homogenous areas. Data for the smallest subnational unit, disaggregated by urban and rural is used. But for some countries the subnational units used are quite large. The sensitivity of the indicator to this assumption was tested by estimating upper and lower bounds, which instead assume the maximum and minimum overlap between the exposed and vulnerable population, respectively. This robustness check suggests the assumption does not have a large impact on results, with the difference between upper and lower bounds less than one percentage point in statistical areas accounting for most of the global population.
    b. *Data on multiple dimensions of vulnerability:* A person is identified as vulnerable if they are lacking on at least one dimension. This requires information on multiple dimensions of vulnerability for the same individual. Often data on all dimensions is not collected for the same individual and there is a need to fuse data from different survey sources. The approaches used for doing this were tested where possible, but further work on methods for fusing is warranted, as well as ongoing efforts to improve household surveys to ensure that all indicators are collected in the same survey where possible. 
    c. *Limited data availability:* In some cases, data that is needed to measure vulnerability is not available. For example, not all surveys have information on access to basic water, and data on access to improved water has to be used for some countries. Similarly, data on beneficiaries and contributors to social protection is not available for all countries, requiring modelled estimates to be used for some countries. Ability to access health services is currently only captured through the general accessibility index and work is ongoing to assess how to bring in other aspects of access to health services. In many cases data on the different dimensions of vulnerability is not up to date, and data for different years have to be used. Continued data investments are needed in household survey data to ensure this measure becomes more accurate over time. 
